defaults:
  - /model/modules/blocks@conv_block: symmetric_conv_next_block
  - /model/modules/blocks@down_sampling_block: avg_pool
  - /model/modules/blocks@recurrent_block: conv_gru_block

_target_: modulus.models.dlwp_healpix_layers.healpix_encoder.UNetEncoder
_recursive_: false
n_channels:
 - 384
 - 192
 - 192
dilations:
  - 1
  - 2
  - 4
