defaults:
  - modules/encoder@encoder: encoder_symmetric_conv_256_128_128
  - modules/decoder@decoder: decoder_symmetric_conv_128_128_256

_target_: modulus.models.dlwp_healpix.HEALPixRecUNet
_recursive_: false
presteps: 1
input_time_dim: ${data.input_time_dim}
output_time_dim: ${data.output_time_dim}
delta_time: ${data.time_step}

# Parameters automatically overridden in train code
input_channels: 7
output_channels: 7
n_constants: 2
decoder_input_channels: 1

# some perf parameters
enable_nhwc: false
enable_healpixpad: true
